name: lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python-quality-checks:
    name: Python quality checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==1.8.2
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: poetry install
      - name: Lint
        run: poetry run ruff check .
      - name: Check formatting
        run: poetry run ruff format --check .
      - name: Type checking
        run: poetry run mypy infrastructure
  rust-quality-checks:
    name: Rust quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: rustfmt
        run: cargo fmt --all --check
      - name: tests
        run: cargo test
